# Este es un flujo de trabajo básico para ayudarte a comenzar con Actions
name: CI
# Controla cuándo se ejecutará el flujo de trabajo
on:
  # Activa el flujo de trabajo en eventos de push o pull request, para todas las ramas
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña de Actions
  workflow_dispatch:
# Una ejecución de flujo de trabajo está compuesta por uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo
jobs:
  # Este flujo de trabajo contiene un solo trabajo llamado "build"
  build:
    # El tipo de runner en el que se ejecutará el trabajo
    runs-on: ubuntu-latest
    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo
    steps:
      # Clona tu repositorio bajo $GITHUB_WORKSPACE, para que tu trabajo pueda acceder a él
      - uses: actions/checkout@v4
      # Ejecuta comando para instalar la librería Jest
      - name: Instalar dependencias
        run: npm install --save-dev jest
      # Ejecuta comando para realizar los test
      - name: Ejecutar los test
        run: npm test
